export const UPDATE_INGREDIENT_LIST = 'UPDATE_INGREDIENT_LIST';
export const UPDATE_DRINK_LIST = 'UPDATE_DRINK_LIST';
export const SET_RESTOCK = 'SET_RESTOCK';
export const UPDATE_INGREDIENT = 'UPDATE_INGREDIENT';
